### ISSUE TITLE
NET.PI.BID

### ISSUE THREAD

**Issue by NET6666STREEM** [DefiProofAudits/smart-contract-audits-#2]
I buy Pi coin 🪙 at the sweetest rate guys message 📨 me now for successful deal ✅pi network and  we also buy accounts that have been KYC approved 📥 Mashallah ✨

WhatsApp contact:
 ‪+44 7570 981162‬

**Comment by DefiProofAudits** [comment]
Salaam alaikum
Are you interested in doing kyc with us ..?
Kindly contact our admin on telegram for more details and fast replies

https://t.me/DeFiProofAudit

Mashallah
